name: test

on:
  push:
    branches:
      - main

jobs:
  test-windows:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Update PATH in Windows
        run: |
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.poetry\bin"
          Get-Content -Path $env:GITHUB_PATH

      - name: Configure poetry
        run: |
          poetry config experimental.new-installer false
          poetry config virtualenvs.in-project true

      - name: Poetry Cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: .venv
          key: venv-${{ matrix.task }}-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      # This is from <https://github.com/python-poetry/poetry/blob/639d5e057/.github/workflows/main.yml#L57-L60>
      - name: Ensure cache is healthy
        if: steps.poetry-cache.outputs.cache-hit == 'true'
        shell: bash
        run: |
          timeout 10s poetry run pip --version || rm -rf .venv



          
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - run: |
          source $VENV
      - name: Export requirements file from lock file
        run: |
          poetry export -f requirements.txt --output requirements.txt          
      - name: Build the executable
        run: |
          poetry run pyoxidizer build
      - name: Create zip of the build
        run: |
          python -c "import shutil; shutil.make_archive('release', 'zip', 'build/dist/')"
      - uses: actions/upload-artifact@v3
        with:
          name: testnicegui
          path: |
            release.zip
